#cloud-config
groups:
  - ubuntu: [root,sys]

users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsjFGM8n1GSr6XmOcNd4y/ZoutH8sfVHg/6VEhJcOp/D7kxNco43YdLbIRzwvsDGYr/ZVxPg1ESCnVHtJlLTip9fntiMzZPlfJVV09uha9di3vXTLg2XSnQRfNeAg1lVGSkLHPD5d7zJb6kOCIJEXwc+MqdxljeFFTwrUCEJsKMD+THAZhZH6STmvA8QJwK9egiYDzvSuc51HhYM1OgS9eSiK5ta5Qu2rhr3XO0EbTuik63HdqYVsKlZjNeLMLT+/sL2UKFOYCOdSoLpsbned2LS9HmhKqXUJw6aLWDZgOgQjddWgoWVF2XDBrhKsHBHCfyVGsvMhGZ/2O1pU8Mn74OxTBZqI59CXh5stqxMb5PesXdmrM6XkFq5TS1snVSn9CCjQ9n3DEgiFZGZYDhBmzqijaVSFLa6Hk8NiqzciS8gfccnDgM7QBq/Jbh0PWlMVu/rwrVedYbJrFtJzJoLEUPwwYRMk7g00SjzDlE46TlU8nxQ/e7GIRutFqCPGzlj0= crafty@crafty-end
packages:
  - docker
  - docker-compose
  - git

runcmd:
  - sudo su terraform
  - cd /home/terraform
  - git clone https://github.com/Crafty-Codes/elastic.git elastic
  - chown terraform:terraform elastic/
  - cd elastic
  - curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o ./docker-compose
  - chmod +x ./docker-compose
  - until docker ps | grep -i -q "container id"; do sleep 5; done;
  - ./docker-compose up
